name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  bloc_handler:
    path: ../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
