name: bloc_handler
description: Bloc handler mixin package.
version: 1.0.1
repository: https://github.com/ivangalkindeveloper/bloc_handler

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
